version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: pg17
    restart: unless-stopped
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5433:5432" 
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d:Z
